NDefines.NCountry.COUNTRIES_GETTING_SCORE = 0
NDefines.NMilitary.WARGOAL_MAX_BONUS = 35
NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200

NDefines.NCountry.PS_ASSAULT = 50

NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 0
NDefines.NCountry.PS_REPLACE_RIVAL = 0

NDefines.NCountry.NAT_FOCUS_YEARS = 15

STABHIT_FOR_BREAKING_ALLIANCE_IN_WAR = 0 -- Alliance System

CELESTIAL_EMPIRE_MANDATE_PER_HUNDRED_DEVASTATION = -0.5
